name: logic_health
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0
  provider: ^6.1.5+1
  material_symbols_icons: ^4.2892.0
  google_fonts: ^6.3.3
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoI.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: qwerty
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
